//! Cordis plugins mounted in a Rust application, with Rust bindings
//! generated at build time from their type declarations (feature `cordis`).
//!
//! The application's `build.rs` calls [`build::from_manifest`], which reads
//! `[package.metadata.rutis-cordis]` from its Cargo.toml and generates one
//! module per mount; [`include_mounts!`](crate::include_mounts) declares
//! them. Each mount runs its plugins in a Node runtime
//! (`@arcships/rutis-runtime`) and projects their services as typed rutis
//! services. The generated code names what it uses through this module.

// Inside the crate, this code names session and runtime items through here.
#[allow(unused_imports)]
pub(crate) use crate::runtime::*;

pub mod build;
#[cfg(unix)]
pub mod server;

pub use crate::runtime::{EmitToCordis, Events, Host, Mount, Process, Projection};
/// What generated code uses, by the paths it names them with.
pub use crate::session as rpc;
pub use crate::session::{
    arg, decode, decode_value, native_error, nullable, optional, Error, JsError, ObjectRef,
    RemoteFunction, PROTOCOL,
};
pub use crate::session::{host_key, HostDispatch};
pub use serde;
pub use serde_json;

/// Environment variable naming the npm project the mounts load from, for a
/// binary running against a deployed copy of it.
pub const ROOT_VARIABLE: &str = "RUTIS_CORDIS_ROOT";

/// The npm project the generated mounts load their runtime and plugins from:
/// [`ROOT_VARIABLE`] when set, else `built`, where it was at build time.
pub fn npm_root(built: &str) -> std::path::PathBuf {
    std::env::var_os(ROOT_VARIABLE)
        .map(std::path::PathBuf::from)
        .unwrap_or_else(|| built.into())
}

/// Declare every mount configured in `[package.metadata.rutis-cordis]` as a
/// module (generated by [`build::from_manifest`]), e.g. `credentials::Plugin`.
#[macro_export]
macro_rules! include_mounts {
    () => {
        include!(concat!(env!("OUT_DIR"), "/rutis_bridge_mounts.rs"));
    };
}
